# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2.1

executors:
  content-executor:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_LOGIN  # can specify string literal values
          password: $DOCKERHUB_TOKEN  # or project environment variable reference
    working_directory: ~/repo

jobs:
  validate-content:
    executor: content-executor
    steps:
      - run:
          name: checkout repo
          command: |
            if [ "${CIRCLE_BRANCH}" == "" ]; then
                git clone https://${GITHUB_TOKEN}@github.com/guilhemmarchand/TA-jira-service-desk-simple-addon
            else
                git clone --branch ${CIRCLE_BRANCH} https://${GITHUB_TOKEN}@github.com/guilhemmarchand/TA-jira-service-desk-simple-addon
            fi
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "TA-jira-service-desk-simple-addon/TA-jira-service-desk-simple-addon/default/app.conf" }}
      - run:
          name: run appinspect API app vetting
          command: |
            cd TA-jira-service-desk-simple-addon
            rm -rf TA-jira-service-desk-simple-addon/.git
            rm -rf TA-jira-service-desk-simple-addon/.circleci
            rm -rf TA-jira-service-desk-simple-addon/.gitignore
            tar -zcf TA-jira-service-desk-simple-addon.tar.gz TA-jira-service-desk-simple-addon
            mkdir dist
            cp TA-jira-service-desk-simple-addon.tar.gz dist/
            cd ../
            TA-jira-service-desk-simple-addon/build/appinspect_vetting.sh $SPLUNK_BASE_LOGIN $SPLUNK_BASE_PASSWD TA-jira-service-desk-simple-addon/dist/TA-jira-service-desk-simple-addon.tar.gz
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "TA-jira-service-desk-simple-addon/TA-jira-service-desk-simple-addon/default/app.conf" }}
          paths:
            - "venv"
      - persist_to_workspace:
          root: TA-jira-service-desk-simple-addon/dist/
          paths:
              - TA-jira-service-desk-simple-addon.tar.gz
  publish-github-release:
    docker:
      - image: cibuilds/github:latest
        auth:
          username: $DOCKERHUB_LOGIN  # can specify string literal values
          password: $DOCKERHUB_TOKEN  # or project environment variable reference
    steps:
      - attach_workspace:
          at: ~/TA-jira-service-desk-simple-addon/dist/TA-jira-service-desk-simple-addon.tar.gz
      - run:
          name: publish release on github
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ~/TA-jira-service-desk-simple-addon/dist/TA-jira-service-desk-simple-addon.tar.gz
workflows:
  version: 2.1
  validate-and-build:
    jobs:
      - validate-content:
          context: 
            - docker-hub-creds
            - splunk-base-creds
          filters:
            tags:
              only: /.*/
      - publish-github-release:
          context: docker-hub-creds
          requires:
            - validate-content
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

